language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    - python ./blog/fixture/load.py
    - coverage run --source=blog -m unittest discover


after_success:
    - coveralls
