language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    - python manage.py db create
    - python manage.py load_data
    - coverage run --source=blog -m unittest discover


after_success:
    - coveralls
