language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - coverage run --source=blog -m unittest discover


after_success:
    - coveralls
